# shopeasy/render.yaml
databases:
  # Not using a PostgreSQL database instance for now since SQLite is specified.

services:
  - type: web
    name: shopeasy-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///shopeasy_v2.db
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
